name: PoseContrast
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cudatoolkit=10.2
  - matplotlib
  - numpy
  - kitsune.one::python-blender
  - tqdm
  - pip
  - pandas